env: flex
runtime: nodejs
manual_scaling:
  instances: 1
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /static
     static_dir: build/static
  - url: /manifest.json
    static_files: build/manifest.json
    upload: build/manifest.json
  - url: /asset-manifest.json
    static_files: build/asset-manifest.json
    upload: build/asset-manifest.json
  - url: /service-worker.json
    static_files: build/service-worker.json
    upload: build/service-worker.json
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)