image: lakoo/node-gcloud-docker

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  only:
    - merge_requests
  
  
production:
  stage: deploy
  script:
    - echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud config set project hsbc-roboadvisor
    - npm install
    - npm run build
    - gcloud app deploy app.yml
  only:
    - master
